var aryso = 
[
    {"img": "soimg-1c.jpg", "final": true, "saying": "The solution is to become your own loving parent."},
    {"img": "soimg-2g.jpg", "final": true, "saying": "As ACA becomes a safe place for you, you will find freedom to express all the hurts and fears you have kept inside and to free yourself from the shame and blame that are carryovers from the past."},
    {"img": "soimg-3a.jpg", "final": true, "saying": "You will become an adult who is imprisoned no longer by childhood reactions."},
    {"img": "soimg-4b.jpg", "final": true, "saying": "You will recover the child within you, learning to accept and love yourself."},
    {"img": "soimg-5a.jpg", "final": true, "saying": "The healing begins when we risk moving out of isolation."},
    {"img": "soimg-6b.jpg", "final": false, "saying": "Feelings and buried memories will return."},
    {"img": "soimg-7c.jpg", "final": false, "saying": "By gradually releasing the burden of unexpressed grief, we slowly move out of the past."},
    {"img": "soimg-8d.jpg", "final": false, "saying": "We learn to re-parent ourselves with gentleness, humor, love and respect."},
    {"img": "soimg-9b.jpg", "final": true, "saying": "This process allows us to see our biological parents as the instruments of our existence."},
    {"img": "soimg-10e.jpg", "final": true, "saying": "Our actual parent is a Higher Power whom some of us choose to call God."},
    {"img": "soimg-11b.jpg", "final": true, "saying": "Although we had alcoholic or dysfunctional parents, our Higher Power gave us the Twelve Steps of Recovery."},
    {"img": "soimg-12b.jpg", "final": true, "saying": "This is the action and work that heals us: we use the Steps; we use the meetings; we use the telephone."},
    {"img": "soimg-13d.jpg", "final": false, "saying": "We share our experience, strength, and hope with each other."},
    {"img": "soimg-14d.jpg", "final": true, "saying": "We learn to restructure our sick thinking one day at a time."},
    {"img": "soimg-15a.jpg", "final": false, "saying": "When we release our parents from responsibility for our actions today, we become free to make healthful decisions as actors, not reactors."},
    {"img": "soimg-16b.jpg", "final": true, "saying": "We progress from hurting, to healing, to helping."},
    {"img": "soimg-17a.jpg", "final": false, "saying": "We awaken to a sense of wholeness we never knew was possible."},
    {"img": "soimg-18b.jpg", "final": true, "saying": "By attending these meetings on a regular basis, you will come to see parental alcoholism or family dysfunction for what it is: a disease that infected you as a child and continues to affect you as an adult."},
    {"img": "soimg-19d.jpg", "final": false, "saying": "You will learn to keep the focus on yourself in the here and now."},
    {"img": "soimg-20b.jpg", "final": true, "saying": "You will take responsibility for your own life and supply your own parenting."},
    {"img": "soimg-21b.jpg", "final": false, "saying": "You will not do this alone."},
    {"img": "soimg-22a.jpg", "final": false, "saying": "Look around you and you will see others who know how you feel."},
    {"img": "soimg-23a.jpg", "final": false, "saying": "We will love and encourage you no matter what."},
    {"img": "soimg-24a.jpg", "final": false, "saying": "We ask you to accept us just as we accept you."},
    {"img": "soimg-25a.jpg", "final": true, "saying": "This is a spiritual program based on action coming from love."},
    {"img": "soimg-26a.jpg", "final": true, "saying": "We are sure that as the love grows inside you, you will see beautiful changes in all your relationships, especially with God, yourself, and your parents."}
];